plugins/qeta-backend/migrations/20230314-search-index.js, plugins/qeta-backend/src/database/DatabaseQetaStore.test.ts, plugins/qeta-backend/src/database/DatabaseQetaStore.ts, plugins/qeta-backend/src/database/QetaStore.ts, plugins/qeta-backend/src/service/router.ts, plugins/qeta/src/api/QetaApi.ts, plugins/qeta/src/components/QuestionsContainer/QuestionsContainer.tsx, plugins/qeta/src/utils/hooks.ts
Initial implementation on adding full text search for the questions page and need some feedback :)
Also needs some cleanup/tweaking before ready.
Currently this implementation only works when using Postgres as the database as I added a GIN index for the concatenation of the title and content, we can then use the full text search capabilities of Postgres to search for questions based on both the title and content of questions.
However, the basic test I added breaks as this approach is not supported by SQLITE.
I don't know how committed you are to supporting both SQLITE and Postgres going forward but I see some different options.
1. Opt for a simpler solution that is supported by both SQLITE and Postgres, something like `WHERE LOWER(questions.content) LIKE LOWER(%query%)`. (Might not scale …
=> feat: full text search on questions page

plugins/qeta/src/components/QuestionsContainer/QuestionsContainer.tsx
This fixes the initial flicker when loading the questions page.
The function in the debounce was called on load and set the filter even though the searchQuery was empty, which in turn triggered another api call.
With this change there should be no extra api calls if you type something and then quickly go back to what you had in the search bar before.
=> fix: filter updated on load when searchQuery not changed

plugins/qeta/src/components/QuestionsContainer/QuestionList.tsx, plugins/qeta/src/components/TagPage/TagsContainer.tsx
Changing the Skeleton to a progress indicator in the QuestionList seems to take care of the flickering.
The progress indicator starts to show after around 300ms, easy to test by applying network throttling in the chrome devtools.
I don't know if using this goes against a design philosophy, if that is the case just ignore this :) 
If you want to go this route I think there could be more places to change this in.
=> fix: flickering on questions page due to skeleton

plugins/qeta-backend/package.json, plugins/qeta-backend/src/service/router.ts
We (the permission framework maintainers) updated the correct usage of createPermissionIntegrationRouter, but the docs remained outdated. As part of fixing the docs (https://github.com/backstage/backstage/pull/17388) we're making PRs to help fix the issue in community plugins as well.
=> fix: Add missing createPermissionIntegrationRouter call

plugins/qeta-backend/package.json, plugins/qeta-backend/src/database/DatabaseQetaStore.ts, plugins/qeta-backend/src/database/QetaStore.ts, plugins/qeta-backend/src/service/router.test.ts, plugins/qeta-backend/src/service/router.ts, plugins/qeta-backend/src/service/standaloneServer.ts, plugins/qeta-backend/src/utils/utils.ts, plugins/qeta-common/src/index.ts, plugins/qeta-common/src/types.ts, plugins/qeta/src/api/QetaApi.ts, plugins/qeta/src/api/QetaClient.ts, plugins/qeta/src/api/types.ts, yarn.lock
Internally, we are looking for ways to improve our Q&A engagement and give more visibility to the people who tend to help with both questions and answers.
Our initial idea is to create a component that can be used on the homepage and show who the users are with the best questions and answers, eventually we want to reward these people internally with some gifts ❤️ 
In order not to complicate the implementations, we thought of adding some simple aggregation endpoints and using them in a ranking.
We also find it interesting to have the data of the person who is logged into the backstage.
We have a small **sketch** of how we imagine this component.
Response sample:
Feedbacks are very welcome, this is just a first suggestion :)
=> feat(statistics): create user statistics endpoints

plugins/qeta/src/api/QetaClient.ts
Fix the behavior that the tab of _Top Upvoted Questions_ was equal to _Top Upvoted Correct Answers_
=> fix(bug-stats-card): fix wrong path TopUpvotedCorrectAnswers

plugins/qeta-backend/src/database/DatabaseQetaStore.ts
- Currently when created a new question is only returned the id field. Thus, when using event broker, the payload of the created question is sent uncompleted. 
Question object returned from `database.postQuestion`:
```
{
id: 1,
author: undefined,
title: undefined,
content: undefined,
created: undefined,
updated: undefined,
updatedBy: undefined,
score: 0,
views: 0,
answersCount: 0,
correctAnswer: false,
favorite: false,
tags: [],
answers: undefined,
votes: undefined,
entities: [],
trend: 0,
comments: undefined
}
```
- Added the fields `id`, `author`, `title`, `content`, `created` to return when created a new question.
=> fix(questions): returning fields on post question

plugins/qeta/src/components/AskPage/AskPage.tsx
This PR adjusts the entity ask page to include the entity's name, so that it's clear to the user what they are asking a question about (and why the entity picker does not appear). This mirrors the logic on the question list page.
Here's what this looks like:
=> feat: use entity title on entity ask page

CONTRIBUTING.md, app-config.yaml, docs/config.md, docs/setup.md, plugins/qeta-backend/configSchema.d.ts, plugins/qeta-backend/src/database/DatabaseQetaStore.test.ts, plugins/qeta-backend/src/database/DatabaseQetaStore.ts, plugins/qeta-backend/src/database/QetaStore.ts, plugins/qeta-backend/src/service/router.test.ts, plugins/qeta-backend/src/service/routes/answers.ts, plugins/qeta-backend/src/service/routes/questions.ts, plugins/qeta-backend/src/service/types.ts, plugins/qeta-backend/src/service/util.ts
The backend APIs work nicely when importing content.  The only hitch is that you can't import content with a creation time or attribution, so all Q&A entries appear as if they were created today by the user who ran the load.
This PR adds an `allowMetadataInput` config flag that, when enabled, allows `created` and `author` fields to be passed along in the POST request to override the default handling.  Normally this should be flagged false except during initial import or loading.
One major area of change is that previously the DatabaseQetaStore always used the current time as the `created` value. This PR requires that a `created` value is explicitly passed into persistence functions.  This PR also adds a `getCreated` function to the utils in parallel to `getUsername` that either accepts …
=> feat: when allowMetadataInput is enabled, accept created and user fields

plugins/qeta-backend/src/search/collators/QetaCollatorFactory.ts
As proposed in #78 these changes were done to have a more descriptive document in `QetaCollatorFactory`.
As a result of these changes the qeta document will look like this:
```json
{
"document": {
"title": "Hello Ask",
"text": "Hello this is a sample question",
"location": "/qeta/questions/1",
"docType": "qeta",
"author": "user:default/user",
"score": 1,
"answerCount": 1
}
}
```
Now these values can be leveraged in the client side to show users more details about qeta searches.
* This PR Closes #78
=> refactor: added relevant qeta document values

plugins/qeta/src/components/QuestionsContainer/QuestionsContainer.tsx
solves issue https://github.com/drodil/backstage-plugin-qeta/issues/112 by reset page parameter like when we filter something
I used the same function used in filters onPageChange(1)
I've created 6 questions and I moved to page 2
Then I have search for "teste 5" (and now the page returned to page 1)
=> feat: searching resets the page

plugins/qeta/src/components/QuestionsContainer/QuestionsContainer.tsx
We would like to have more data on the qeta search so that we can better understand how people are using our engineering.
I was inspired by the use of the other analytics calls in the plugin.
=> feat: add analytics events to search

plugins/qeta/src/components/QuestionPage/VoteButtons.tsx
The check icon when the correct answer is not being colored, should be styled as green.
**Before:**
**After**
=> fix: selected correct answer color

docs/config.md, package.json, plugins/qeta-backend/configSchema.d.ts, plugins/qeta-backend/package.json, plugins/qeta-backend/src/service/routes/attachments.ts, plugins/qeta-backend/src/service/upload/s3.ts, yarn.lock
Upgrading `aws-sdk` to v3 (v2 is deprecated) and also included the option to pass region for s3, otherwise it fails to find the AWS keys on environments where region is not configured globally.
=> chore: update aws-sdk to v3 and accept s3 region

plugins/qeta/src/components/Links/Links.tsx
Possible fix for issue: https://github.com/drodil/backstage-plugin-qeta/issues/152.
The if-statement in UserLink won't be executed at the moment if the entityRef is actually 'anonymous' as it will then always crash when executing `useEntityPresentation`.
A possible fix could be to move the check to the `AuthorLink` component as this PR suggests.
Not sure if it would need to be added in more places, like `UpdatedByLink` for example.
=> fix: add user prefix to entityRef in UserLink

plugins/qeta/src/components/QuestionsContainer/FilterPanel.tsx, plugins/qeta/src/components/QuestionsContainer/QuestionsContainer.tsx
Removed showEntityFilter value setting based on entity query parameter and removing duplicate entity ref value from available entities list.
=> fix: Fixed issue #152, entity filter disappear on select and selected entity showing twice in dropdown

plugins/qeta-backend/src/plugin.ts
Fixed issue #157
Tested preview with uploaded image:
Test question details page:
=> fix: image download broken after migrate to new backend system with default auth policy

app-config.yaml, docs/config.md, docs/permissions.md, plugins/qeta-backend/configSchema.d.ts, plugins/qeta-backend/dev/PermissionPolicy.ts, plugins/qeta-backend/dev/index.ts, plugins/qeta-backend/package.json, plugins/qeta-backend/src/conditionExports.ts, plugins/qeta-backend/src/database/DatabaseQetaStore.test.ts, plugins/qeta-backend/src/database/DatabaseQetaStore.ts, plugins/qeta-backend/src/database/QetaStore.ts, plugins/qeta-backend/src/index.ts, plugins/qeta-backend/src/plugin.ts, plugins/qeta-backend/src/service/questionRules.ts, plugins/qeta-backend/src/service/router.test.ts, plugins/qeta-backend/src/service/router.ts, plugins/qeta-backend/src/service/routes/answers.ts, plugins/qeta-backend/src/service/routes/questions.ts, plugins/qeta-backend/src/service/util.ts, plugins/qeta-common/src/permissions.ts, plugins/qeta-common/src/types.ts, plugins/qeta/src/components/CommentSection/CommentSection.tsx, plugins/qeta/src/components/QuestionPage/QuestionCard.tsx, yarn.lock
Better authorization of users incoming. Relates to https://github.com/backstage/backstage/issues/23845
=> feat: wip change to permission framework

docs/search.md, plugins/qeta/dev/SearchPage.tsx, plugins/qeta/src/components/QetaSearchResultListItem/QetaSearchResultListItem.tsx, plugins/qeta/src/components/QetaSearchResultListItem/index.ts, plugins/qeta/src/components/index.ts, plugins/qeta/src/index.ts, plugins/qeta/src/plugin.ts
This PR refactors the search result handling in the `qeta` plugin, simplifying rendering logic and improving modularity. The main changes focus on streamlining the `searchPage` component, enhancing type consistency, and refining exports for better reusability.
- **Simplified search result rendering** by replacing redundant logic with a direct usage of `QetaSearchResultListItem`.
- **Improved type consistency** by renaming and refining `QetaSearchResultListItemProps`.
- **Enhanced module exports** to ensure better accessibility and modularity.
- **Introduced a Backstage search result extension** for structured integration within the search framework.
- **Better maintainability** with reduced complexity in `searchPage`.
- **Improved type safety** and clearer component definitions.
- …
=> feat(search): add support to search result item extensions

plugins/qeta-backend/src/service/routes/answers.ts, plugins/qeta-backend/src/service/routes/posts.ts
currently, "New Mention" notifications are sent to every subscriber rather than the user that was mentioned
=> fix parameter order of onMention calls

plugins/qeta-react/src/components/MarkdownEditor/MarkdownEditor.tsx
This pull request refines the logic in the `MarkdownEditor` component to improve the handling of entity suggestions. The changes ensure better filtering of enabled mention types and add a safeguard for cases where no text or enabled kinds are provided.
* [`plugins/qeta-react/src/components/MarkdownEditor/MarkdownEditor.tsx`](diffhunk://#diff-80aabd2bbbc7f85cf08ef7345e83d9525cb221362e86502256b5169b59d10dd9L165-R174): Changed the filtering logic to ensure `enabledMentionTypes` are checked against `supportedKinds` instead of the reverse, improving clarity and correctness.
* [`plugins/qeta-react/src/components/MarkdownEditor/MarkdownEditor.tsx`](diffhunk://#diff-80aabd2bbbc7f85cf08ef7345e83d9525cb221362e86502256b5169b59d10dd9L165-R174): Added a condition to return an empty suggestions array …
=> fix: avoid querying when no mention kinds are enabled

plugins/qeta-backend/dev/index.ts, plugins/qeta-backend/src/plugin.ts, plugins/qeta-backend/src/service/NotificationManager.test.ts, plugins/qeta-backend/src/service/NotificationManager.ts, plugins/qeta-backend/src/service/router.ts, plugins/qeta-backend/src/service/types.ts, plugins/qeta-node/src/extensions.ts
Add notification receivers extension point that can be used to specify custom recipients for notifications.
The main use case for this is to enable dynamic selection of notification recipients based on external data sources, like another plugin or a third-party integration, especially in scenarios where relying on static tag experts is falls short.
=> feat: notification receivers extension point
